"""
Django settings for django_cms_base project.

Generated by 'django-admin startproject' using Django 1.9c1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SITE_ID = 1

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/



##################################################################
##################################################################
##### This secret key in generated on each install change it #####
##################################################################
##################################################################


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'uj!wc*ukfxfo)e4k4k_6@48j)616#n3frimk9d-x%pt7km2i8d'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
DJANGO_APPS = (
    # Default Django apps:
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.redirects',

    # Useful template tags:
    'django.contrib.humanize',

    # Admin
    'django.contrib.admin',
    # 'django.contrib.admin.apps.SimpleAdminConfig',
)

THIRD_PARTY_APPS = (
    # CMS
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'djangocms_style',
    'djangocms_column',
    'easy_thumbnails',
    'filer',
    'mptt',
    'cmsplugin_filer_image',
    'cmsplugin_filer_file',
    'cmsplugin_filer_utils',
    'cmsplugin_filer_video',
    'djangocms_link',
    # 'cmsplugin_contact_plus',
    'djangocms_forms',
    'django_mobile',
    # 'reversion',
)

# Apps specific for this project go here.
LOCAL_APPS = (
    # 'landcare.apps.cms_slider',
    # 'landcare.apps.cms_bgimage',
    # 'landcare.apps.cms_position',
    # 'landcare.apps.cms_service',
    # 'landcare.apps.cms_teams',
    # 'landcare.apps.cms_events',
    # 'landcare.apps.cms_news',
    # 'landcare.apps.cms_statistics',
)

INSTALLED_APPS = LOCAL_APPS + THIRD_PARTY_APPS + DJANGO_APPS

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',

    'django_mobile.middleware.MobileDetectionMiddleware',
    'django_mobile.middleware.SetFlavourMiddleware',
]


ROOT_URLCONF = 'app_name.urls' # change this to the project name 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(os.path.normpath("%s/../" % os.path.dirname(__file__)), 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',

                # Your stuff: custom template context processors go here
                'cms.context_processors.cms_settings',
                'sekizai.context_processors.sekizai',
                'django_mobile.context_processors.flavour',
            ],
        },
    },
]

CMS_TEMPLATES = (
    ('home.html', 'Homepage'),
)

CMS_STYLE_NAMES = (
    ('row', _("Row")),
)

THUMBNAIL_HIGH_RESOLUTION = True

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    #'easy_thumbnails.processors.scale_and_crop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)

MIGRATION_MODULES = {
    'cmsplugin_filer_file': 'cmsplugin_filer_file.migrations_django',
    'cmsplugin_filer_folder': 'cmsplugin_filer_folder.migrations_django',
    'cmsplugin_filer_link': 'cmsplugin_filer_link.migrations_django',
    'cmsplugin_filer_image': 'cmsplugin_filer_image.migrations_django',
    'cmsplugin_filer_teaser': 'cmsplugin_filer_teaser.migrations_django',
    'cmsplugin_filer_video': 'cmsplugin_filer_video.migrations_django',
}

WSGI_APPLICATION = 'app_name.wsgi.application' # change this to the project name 

# Additional locations of static files
STATICFILES_DIRS = (
    os.path.normpath(os.path.join(BASE_DIR, 'static')),
)

# Form Plugin Variables
DJANGOCMS_FORMS_PLUGIN_MODULE = _('Generic')
DJANGOCMS_FORMS_PLUGIN_NAME = _('Form')
DJANGOCMS_FORMS_DEFAULT_TEMPLATE = 'djangocms_forms/form_template/default.html'
DJANGOCMS_FORMS_USE_HTML5_REQUIRED = True
DJANGOCMS_FORMS_WIDGET_CSS_CLASSES = {'__all__': ('form-control', ) }

# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en-us', 'English'),
]

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True