#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# productivity
cookbook 'git'
cookbook 'apt'
cookbook 'newrelic', '~> 2.15.1'

# Cache Layer
cookbook 'memcached'
cookbook 'varnish'

# Servers
cookbook 'nginx'
cookbook 'python'
cookbook 'uwsgi'
cookbook 'mysql'
cookbook 'database'
